# Generated by Django 4.2.11 on 2025-03-06 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stabilimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Macchinario',
            fields=[
                ('codiceMacchinario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('modello', models.CharField(max_length=24)),
                ('stabilimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.stabilimento')),
            ],
        ),
    ]
