# Generated by Django 4.2.11 on 2025-03-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macchinario',
            fields=[
                ('codiceMacchinario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('modello', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Stabilimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=5)),
                ('macchinario_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macchinario_turno', to='gestione.macchinario')),
            ],
        ),
        migrations.AddField(
            model_name='macchinario',
            name='stabilimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macchinario', to='gestione.stabilimento'),
        ),
    ]
