# Generated by Django 4.2.11 on 2025-03-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_workhour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhour',
            name='hours_worked',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
