# Generated by Django 4.2.11 on 2025-03-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_alter_workhour_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stabilimento',
            name='id',
        ),
        migrations.AddField(
            model_name='stabilimento',
            name='codiceStabilimento',
            field=models.CharField(default='0', max_length=242, primary_key=True, serialize=False),
        ),
    ]
